export const AUTHENTICATE_USER = "AUTHENTICATE_USER"
export const LOG_OUT_USER = "LOG_OUT_USER"

export const SHOW_LOGIN_ERROR = "SHOW_LOGIN_ERROR"

export const SAVE_ITEMS = "SAVE_ITEMS"
export const SAVE_CURRENT_ITEM = " SAVE_CURRENT_ITEM"
export const OPEN_CURRENT_ITEM = "OPEN_CURRENT_ITEM"
export const CLOSE_CURRENT_ITEM = "CLOSE_CURRENT_ITEM"
export const ON_ITEM_TITLE_CHANGE = "ON_ITEM_TITLE_CHANGE"
export const ON_ITEM_IMAGE_CHANGE = "ON_ITEM_IMAGE_CHANGE"
export const ON_ITEM_PAGE_URL_CHANGE = "ON_ITEM_PAGE_URL_CHANGE"
export const ON_ITEM_CSS_SELECTOR_CHANGE = "ON_ITEM_CSS_SELECTOR_CHANGE"
export const ON_ITEM_ATTRIBUTE_NAME_CHANGE = "ON_ITEM_ATTRIBUTE_NAME_CHANGE"
export const ON_ITEM_TRACKING_CHANGE = "ON_ITEM_TRACKING_CHANGE"

export const SAVE_USER = "SAVE_USER"
export const ON_PROFILE_USERNAME_CHANGE = "ON_PROFILE_USERNAME_CHANGE"
export const ON_PROFILE_AVATAR_CHANGE = "ON_PROFILE_AVATAR_CHANGE"
